<?php

namespace App\Models\Order;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Order extends Model {
    protected $table = 'orders';
    protected $fillable = [
        'user_id',
        'order_no',
        'tracking_no',
        'original_no',
        'return_no',
        'send_name',
        'send_tel',
        'send_detail',
        'send_district',
        'send_city',
        'send_province',
        'send_postal_code',
        'recv_name',
        'recv_tel',
        'recv_detail',
        'recv_district',
        'recv_city',
        'recv_province',
        'recv_postal_code',
        'category_code',
        'category_text',
        'weight',
        'length',
        'width',
        'height',
        'is_protect_insurance',
        'is_return_insurance',
        'is_damage_insurance',
        'is_express_transpot',
        'order_cod',
        'order_price',
        'note_detail',
        'user_cod',
        'user_price',
        'signer_name',
        'signer_type',
        'signature_url',
        'operator_id',
        'operator_tel',
        'operator_branch',
        'pickup_id',
        'status_code',
        'status_text',
        'transport_text',
        'price_policy_code',
        'price_policy_text',
        'up_country_fee',
        'protect_value',
        'protect_fee',
        'speed_fee',
        'cod_transport_fee',
        'return_fee',
        'damage_fee',
        'problem_code',
        'problem_text',
        'cancel_reason',
        'source',
        'webhook_weight',
        'webhook_lenght',
        'webhook_width',
        'webhook_height',
        'webhook_order_cod',
        'webhook_order_price',
        'webhook_user_cod',
        'webhook_user_price',
        'webhook_transport_code',
        'webhook_transport_text',
        'webhook_price_policy_code',
        'webhook_price_policy_text',
        'webhook_up_country_fee',
        'webhook_declared_protect_value',
        'webhook_protect_fee',
        'webhook_speed_fee',
        'webhook_cod_transfer_fee',
        'webhook_return_fee',
        'webhook_damage_fee',
        'webhook_packaging_fee',
        'webhook_label_fee',
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }
}
